[build]
	functions = "netlify/functions"
	publish = "public"

[functions]
  node_bundler = "esbuild"

[functions."create-skate-poll"]
	schedule = "0 8 * * 2"

[functions."create-skate-poll"]
	schedule = "0 8 * * 4"